# Generated by Django 2.0 on 2017-12-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelProcess', '0003_auto_20171227_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/%Y/'),
        ),
    ]
